### ISSUE TITLE
우측에 여백이 생기는 이슈

### ISSUE THREAD

**Issue by som-syom** [PreOnBoarding-Team17/Week3_MainPage#27]
## ❗️이슈 주제
우측에 여백이 생기는 이슈

Review 배경이미지를 깔다가 우측에 여백이 생기는 부분을 확인하였습니다.

![image](https://user-images.githubusercontent.com/60869490/154008301-bd0b94a2-1bfa-48fd-a16d-f4e757b0b35b.png)

![image](https://user-images.githubusercontent.com/60869490/154008428-84d0255e-bb74-4532-be60-722332bde8a4.png)

컴포넌트 하나씩 가려보다보니 BookDiary 컴포넌트에서 생기는 것 같습니다.
한번 확인해주세요!
@sangseophwang

**Comment by som-syom** [comment]
BookDiary 컴포넌트 쪽 문제가 아니라면 코멘트 달아주시고
내부에서 처리할 수 있는거면 담당자 체크해주시고 여기 이슈에다 수정해주시면 될거같습니다 👍

**Comment by sangseophwang** [comment]
전역에 box-sizing: border-box랑 overflow-x: hidden 적용해놓겠습니다!!

**Comment by sangseophwang** [comment]
이슈 해결했습니다!! 마지막에 제 파트 작업하고 풀리퀘하면 적용될겁니다 :)
